export class Images {
  static readonly LogoFrost = require('./frost-logo.svg')
  static readonly Toogle = require('./toggle.svg')
  static readonly PoetWhite = require('./poet-white.svg')
  static readonly PoetBlack = require('./poet-black.svg')
  static readonly FrostLogoOnly = require('./frost-logo-only.svg')
  static readonly FavIcon = require('./fav.ico')
  static readonly Documentation = require('./documentation.svg')
  static readonly Integrations = require('./integrations.svg')
  static readonly Key = require('./key.svg')
  static readonly NoKey = require('./nokey.svg')
  static readonly Rocket = require('./rocket.svg')
  static readonly KeySmall = require('./key.svg')
  static readonly Book = require('./documentation.svg')
}
