import '../../src/canary.test'
import '../../src/components/atoms/ToggleMainnet/ToggleMainnet.test'
import '../../src/components/atoms/ToggleRP/ToggleRP.test'
import '../../src/configuration.test'
import '../../src/reducers/ChangePassword.reducer.test'
import '../../src/components/containers/CreateToken.container.test.tsx'
import '../../src/reducers/ApiTokens.reducer.test.ts'
import '../../src/reducers/PostWork.reducer.test.ts'