import '../../src/canary.test'
import '../../src/components/atoms/ToggleMainnet/ToggleMainnet.test'
import '../../src/components/atoms/ToggleRP/ToggleRP.test'
import '../../src/reducers/ChangePassword.reducer.test'
import '../../src/components/containers/CreateToken.container.test.tsx'